<?php 
    require "./Aluno.php";

    $alunos = [
        new Aluno("Larissa Ribeiro", 10, 9, 9),
        new Aluno("João Carvalho", 10, 10, 10),
        new Aluno("Beatriz Santos", 10, 5, 6),
        new Aluno("Lucas Oliveira", 5, 10, 10),
        new Aluno("Caio Dantas", 1, 10, 1),
        new Aluno("Eliane Rodrigues", 1, 1, 10),
        new Aluno("Raphaely Oliveira", 1, 10, 10),
        new Aluno("Maria Benfica", 8, 10, 9),
        new Aluno("Pedro Galvão", 5, 10, 8),
        new Aluno("Bruno Gomes", 10, 10, 7),
        new Aluno("Caroline Oliveira", 7, 5, 10),
        new Aluno("Samuel Assunção", 9, 10, 6),
        new Aluno("Ester Santos", 1, 10, 1),
        new Aluno("Isabelle Moraes", 1, 10, 1),
        new Aluno("Davi Matias", 10, 5, 10),
        new Aluno("Gabriel Lemos", 1, 1, 10),
        new Aluno("Igor Roma", 1, 10, 10),
        new Aluno("Beatriz Castilho", 10, 6, 7),
        new Aluno("Luiza Souza", 1, 10, 9),
        new Aluno("Marina Mikie", 10, 8, 7),
        new Aluno("Maria Camargo", 10, 1, 4),
        new Aluno("Debora Nascimento", 10, 6, 7),
        new Aluno("Max Oliveira ", 10, 10, 7),
        new Aluno("Simone Lemes", 10, 1, 10),
        new Aluno("Hellen Damacena", 1, 1, 10),
        new Aluno("Elaine Silva", 1, 10, 1),
        new Aluno("Christian Lima", 8, 10, 1),
        new Aluno("Luana Silva", 1, 10, 1),
        new Aluno("Jhonatas Oliveira", 9, 10, 7),
        new Aluno("Gustavo Rodrigues", 1, 10, 1),
        new Aluno("Julia Morais", 5, 6, 4),
        new Aluno("Fernanda Sarraipa", 4, 10, 7),
        new Aluno("Barbara Castilho", 3, 10, 6),
        new Aluno("Aline Cardoso", 1, 10, 1),
        new Aluno("Isabela Teixeira", 7, 6, 10),
        new Aluno("Adriana Monteiro", 10, 1, 9),
        new Aluno("Diana Souza", 1, 1, 10),
        new Aluno("Letícia Mendes", 1, 1, 10),
        new Aluno("Eliane Rocha", 1, 10, 1),
        new Aluno("Larissa Dantas", 10, 1, 8),
        new Aluno("Milena Melo", 10, 10, 10),
    ];
    echo json_encode($alunos);
?>
